---
- name: create multiple users on AAP
  hosts: localhost
  vars_files:
    - controller-user-data.yml 
  tasks:
    - name: create users
      ansible.controller.user:
        username:  "{{ item.username }}"
        password: "{{ item.password }}"
        email: "{{ item.email }}"
        state: present
        organization: Default
        validate_certs: False
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
      loop: "{{ controller_user_data }}"
