---
- name: create simple user
  hosts: all
  vars:
    linux_user: john
  tasks:
    - name: create user {{ linux_user }}
      ansible.builtin.user:
        name: "{{ linux_user }}"
        state: present
